[build]
  publish = "https://merry-sundae-3393ba.netlify.app//public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"